name: Feature Request
description: Suggest an idea for Content Templates
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in Content Templates, and why?
    validations:
      required: true
